module4-task2
htmlacademy-javascript/977377-keksobooking-21 pull request #6
Opened 2020-11-08 20:03 UTC by Worsto

2020-11-09 19:32 UTC, maraero commented on js/card.js
> +
Если хочешь такие формы и с такой простой логикой (нормальные функции немного посложнее), то лучше тернарники использовать:
```const rooms = element.offer.rooms === 1 ? 'комната' : 'комнаты'```

2020-11-09 19:45 UTC, maraero commented on js/map.js
> +  const mapPins = document.querySelector(`.map__pins`);
А зачем поменял на document?

2020-11-09 19:49 UTC, maraero commented on js/card.js
> +  let offerPin;
Мне не нравится, что ты объявляешь переменную, а присваиваешь непонятно где, в какой-то функции. Супер неявно

2020-11-09 19:49 UTC, Worsto commented on js/map.js
> +  const mapPins = document.querySelector(`.map__pins`);
переносил строки в другие файлы, потом вернул, а это вернуть на место забыл.

2020-11-09 19:52 UTC, Worsto commented on js/card.js
> +  let offerPin;
Вот тут боюсь не обойтись без консультации

2020-11-09 21:49 UTC, maraero commented on js/card.js
> +  function createCloseButton() {
Разве эта функцию создаёт кнопку?

2020-11-09 21:50 UTC, maraero commented on js/card.js
> +      if (offerPin === evt.target.closest(`.map__pin`)) {
Вообще выглядит странно, что функцию называется showCard, а в итоге закрывает.

2020-11-09 21:53 UTC, maraero commented on js/createOffers.js
> +  window.createOffers = function (amount) {
я предпочитаю разделять объявление функцию и "экспорт", но на твой вкус. Удобно разделять, когда экспортов несколько -- просто группируешь их в конце

2020-11-09 21:54 UTC, maraero commented on js/data.js
> +  const offers = window.createOffers(OFFERS_QUANTITY);
Я бы, пожалуй, переименовал модуль. Он явно не за данные отввечает

2020-11-09 21:55 UTC, maraero commented on js/form.js
> -      fieldsets[i].setAttribute(`disabled`, `disabled`);
так значение true можно было поставить и так

2020-11-09 22:01 UTC, maraero requested changes
В целом всё выглядит хорошо! Но давай пройдёмся по омментам, и попробуем сделать поакуратнее?

2020-11-10 05:58 UTC, Worsto commented on js/card.js
> +  function createCloseButton() {
поменял на activateCloseButton()

2020-11-10 05:59 UTC, Worsto commented on js/card.js
> +      if (offerPin === evt.target.closest(`.map__pin`)) {
Поменял на interateWithPin
вынес создание карточки в отдельную функцию

2020-11-10 06:00 UTC, Worsto commented on js/createOffers.js
> +  window.createOffers = function (amount) {
Не совсем понял как разделить

2020-11-12 22:28 UTC, merged